# Page settings

baseurl = ""
languageCode = "en-us"
title = "Daryl Galvez CV"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Daryl Galvez"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Daryl Galvez"
        tagline = "Software Developer/ Marine Engineer"
        avatar = "avatar01.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: daryl.kevin.24@gmail.com"
        title = "daryl.kevin.24@gmail.com"

        # [[params.contact.list]]
        # class = "phone"
        # icon = "fa-phone"
        # url = "tel:+639164064160"
        # title = "+639164064160"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/daryl-galvez"
        title = "linkedin.com/in/daryl-galvez"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//darylgalvez.xyz"
        title = "https://darylgalvez.xyz"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/darylkevin"
        title = "github.com/darylkevin"

        # [[params.contact.list]]
        # class = "twitter"
        # icon = "fa-twitter"
        # url = "//twitter.com/username"
        # title = "@twittername"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Data Engineering - Project SPARTA"
        college = "Development Academy of the Philippines"
        dates = "2020 - Present"

        [[params.education.list]]
        degree = "Introduction to Programming Nanodegree"
        college = "Udacity"
        dates = "2020"

        [[params.education.list]]
        degree = "BS Marine Transportation and Engineering"
        college = "Maritime Academy of Asia and the Pacific"
        dates = "2007 - 2011"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Filipino/ Tagalog"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

        [[params.language.list]]
        language = "Spanish"
        level = "Beginner"

        [[params.language.list]]
        language = "Japanese"
        level = "Beginner"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Cycling and Running"

        [[params.interests.list]]
        interest = "Freediving"

        [[params.interests.list]]
        interest = "Tinkering"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "I am an aspiring software developer and IT professional. I came from a seafaring and engineering background and I hope to contribute my knowledge and experience from my previous work into a new role."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Recruitment Technical Officer"
        dates = "Mar 2020 - Oct 2020"
        company = "Maersk Filipinas Crewing Inc."
        details = "Organized and monitored all technical aspects of seafarer recruitment and talent sourcing. Act as consultant with regards to applicants' technical screening, and promotion evaluation of exisiting crew."

        [[params.jobs.list]]
        position = "Technical Interviewer"
        dates = "Jan 2020 - Mar 2020"
        company = "Maersk Filipinas Crewing Inc."
        details = "Screened applicants and conducted technical interviews to determine their fitness to serve onboard Maersk vessels. Handled both deck department and engine deparment applications."

        [[params.jobs.list]]
        position = "Marine Engineer"
        dates = "Oct 2012 - Jan 2020"
        company = "Maersk A/S"
        details = "Served as marine engineer onboard Maersk Vessels. Started from lowest rank until reaching management level onboard. Responsiblel for the safe and efficient operation of the ship and it's propulsion, power generation, and auxiliary equipment and systems. Initiated operational improvements onboard which resulted in at least 3% savings annually and saved at least USD 8000 by implementing cost-saving initiatives and inventory management that addressed longstanding problems."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        # intro = "**These are some small projects that I have worked on** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Python Adventure Game"
        url = "https://github.com/darylkevin/Python-Adventure-Game"
        tagline = "Udacity Project: A simple text-based adventure game that you can run in a terminal. I am planning to make a GUI version soon."

        [[params.projects.list]]
        title = "Terminal Weather Forcaster"
        url = "https://github.com/darylkevin/weather_api_project"
        tagline = "My take on a lesson in Udacity's Python course. This uses an API which pulls weather forecasts on a specified city and displays the output in the terminal. A GUI version is in the works."

        [[params.projects.list]]
        title = "Animal Trading Cards"
        url = "https://github.com/darylkevin/Animal-Trading-Cards"
        tagline = "Udacity Project: A simple webpage which displays my favorite animal in a 'trading card style' view."

        [[params.projects.list]]
        title = "Pixel Art Maker"
        url = "https://github.com/darylkevin/Pixel-Art-Maker"
        tagline = "Udacity Project: A simple pixel-art maker."

        [[params.projects.list]]
        title = "Personal Website"
        url = "https://darylgalvez.xyz"
        tagline = "My personal website using markdown and Hugo."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Python"
        level = "70%"

        [[params.skills.list]]
        skill = "Javascript"
        level = "55%"

        [[params.skills.list]]
        skill = "Git"
        level = "85%"

        [[params.skills.list]]
        skill = "HTML5 & CSS"
        level = "85%"

        [[params.skills.list]]
        skill = "Linux & *NIX"
        level = "75%"

        [[params.skills.list]]
        skill = "Terminal & Shells"
        level = "70%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
